image: Visual Studio 2022
artifacts:
  - path: '**\*.nupkg'

install:
- ps: |
    Invoke-WebRequest -Uri 'https://dot.net/v1/dotnet-install.ps1' -UseBasicParsing -OutFile "$env:temp\dotnet-install.ps1"
    & $env:temp\dotnet-install.ps1 -Architecture x64 -Version '10.0.100' -InstallDir "$env:ProgramFiles\dotnet"

configuration:
  - Release

build_script:
  - cmd: >-
      dotnet build .\dotnet-repl.sln -p:Version=%APPVEYOR_BUILD_VERSION%

after_build:
  - cmd: >-
      dotnet pack .\src\dotnet-repl\dotnet-repl.csproj -c:release -p:Version=%APPVEYOR_BUILD_VERSION%

test_script:
  - cmd: >-
      dotnet test .\src\dotnet-repl.Tests\dotnet-repl.Tests.csproj